### ISSUE TITLE
Add example for threads (MSC3440) support

### ISSUE THREAD

**Issue by HarHarLinks** [maubot/reactbot#10]
Not entirely sure this is possible as-is, might need to add a `get_thread` function or so, since MSC3440 is a bit more complicated than replies. What currently happens with replies is that I post to a thread but maubot replies in the main timeline. I haven't thought too much about it yet, but maybe somebody already has and can contribute.

**Comment by ajkessel** [comment]
Any possible workaround or fix for this? Reactions in the room rather than the thread typically look completely out of place.

**Comment by tulir** [comment]
This isn't a bug so there's no workaround for fix, it's just a request for an example

**Comment by ajkessel** [comment]
Does that mean it's possible to implement responses-in-threads just by usnig the right template?

**Comment by HarHarLinks** [comment]
> This isn't a bug so there's no workaround for fix, it's just a request for an example

That is assuming this is possible at all yet, and to be understood as a feature request otherwise :)

**Comment by ajkessel** [comment]
Some details [here](https://github.com/slackapi/bolt-js/issues/1370) about how to make a bot respond in a thread, but I'm not sure if this would require patching reactbot or if it's just a template issue.

**Comment by HarHarLinks** [comment]
Awesome, thank you tulir!
