### ISSUE TITLE
Give an example where the reactbot output uses variables from the input it reacts to.

### ISSUE THREAD

**Issue by spaetz** [maubot/reactbot#3]
From the included samples it is unclear if reactbot can draw on the input it reacts to. Let me give an example:

@user1: hello all
@reactbot: Hello user1

or when a users says
user1: I have a black hat.
and reactbot matches "black (+*)\b" it should use the match, e.g. "You have a wonderful HAT". (I hope you get my point)

**Comment by tulir** [comment]
https://github.com/maubot/reactbot/blob/master/samples/nitter.yaml
