### ISSUE TITLE
[feature request] trigger commands when certain reaction thresholds are met

### ISSUE THREAD

**Issue by n1trux** [maubot/reactbot#4]
I have several meme channels. Is it possible to have the bot post 👍️ and 👎️ reactions to every image post, which people can click, and then have the bot remove it if >50% of the users in the room online in the last month have voted 👎️?

Would be nice if the bot could have configurable reactions to reactions in that way. Another idea for which that can be used is if a person reacts with :eyes:, the bot could message them with the contents and a link of that message for reading later.

**Comment by tulir** [comment]
I think both of those are somewhat out of scope. Tracking the number of reactions is at least complicated (probably requires a database if you don't want to forget the count after a restart). Figuring out which other room to send to is also relatively complicated (i.e. fairly easy, but not in a fully stateless match-response bot like this).

Both of those can be done with bots of course, but it's probably better to write a new bot specifically for those (there's a [maubot plugin wishlist](https://github.com/maubot/plugin-wishlist/issues) and [docs for developing plugins](https://docs.mau.fi/maubot/dev/getting-started.html))
